import type {
  Attribute,
  DatabaseEngine,
  RelationalSchema,
  RelationalTable,
} from "../domain/types";
export const quote = (name: string) => "`" + name.replace(/`/g, "``") + "`";
export function sqlType(
  a: Attribute,
  engine: DatabaseEngine = "mysql",
): string {
  if (engine === "postgresql") {
    if (a.type === "DATETIME" || a.type === "TIMESTAMP") return "TIMESTAMP";
    if (a.type === "DECIMAL")
      return `NUMERIC(${a.precision ?? 10},${a.scale ?? 2})`;
  }
  if (a.type === "VARCHAR") return `VARCHAR(${a.length ?? 255})`;
  if (a.type === "DECIMAL")
    return `DECIMAL(${a.precision ?? 10},${a.scale ?? 2})`;
  return a.type;
}
function defaultSQL(a: Attribute): string {
  const value = a.defaultValue;
  if (value === undefined || value === "") return "";
  if (
    /^CURRENT_TIMESTAMP(?:\(\))?$/i.test(value) &&
    ["TIMESTAMP", "DATETIME"].includes(a.type)
  )
    return " DEFAULT CURRENT_TIMESTAMP";
  if (/^CURRENT_DATE(?:\(\))?$/i.test(value) && a.type === "DATE")
    return " DEFAULT (CURRENT_DATE)";
  if (
    ["INT", "BIGINT", "DECIMAL", "BOOLEAN"].includes(a.type) &&
    /^(?:-?\d+(?:\.\d+)?|true|false)$/i.test(value)
  )
    return ` DEFAULT ${value.toUpperCase()}`;
  const literal = "'" + value.replace(/'/g, "''").replace(/\\/g, "\\\\") + "'";
  return " DEFAULT " + (a.type === "TEXT" ? `(${literal})` : literal);
}
export function orderedTables(schema: RelationalSchema): RelationalTable[] {
  const ordered: RelationalTable[] = [],
    visited = new Set<string>(),
    visiting = new Set<string>();
  const visit = (table: RelationalTable) => {
    if (visited.has(table.id) || visiting.has(table.id)) return;
    visiting.add(table.id);
    for (const fk of table.foreignKeys) {
      const parent = schema.tables.find((t) => t.name === fk.referencedTable);
      if (parent) visit(parent);
    }
    visiting.delete(table.id);
    visited.add(table.id);
    ordered.push(table);
  };
  schema.tables.forEach(visit);
  return ordered;
}
export function generateMySQL(
  schema: RelationalSchema,
  projectName = "SchemaForge project",
): string {
  if (!schema.tables.length)
    return "-- Add your first entity to start generating SQL.";
  const ordered = orderedTables(schema);
  const parts = [
    `-- ${projectName.replace(/[\r\n]/g, " ")}\n-- Generated by SchemaForge · MySQL 8.0.16+\n-- Derived from your conceptual model\n`,
  ];
  if (schema.enforcementNotes?.length)
    parts.push(
      "-- Specialization rules requiring additional enforcement\n" +
        schema.enforcementNotes
          .map((note) => "-- " + note.replace(/[\r\n]/g, " "))
          .join("\n"),
    );
  for (const table of ordered) {
    const definitions = table.columns.map(
      (a) =>
        `  ${quote(a.name)} ${sqlType(a)}${!a.nullable || a.primaryKey ? " NOT NULL" : ""}${a.autoIncrement ? " AUTO_INCREMENT" : ""}${defaultSQL(a)}${a.unique && !a.primaryKey ? " UNIQUE" : ""}`,
    );
    const keys = table.columns
      .filter((a) => a.primaryKey)
      .sort((a, b) => Number(b.autoIncrement) - Number(a.autoIncrement))
      .map((a) => quote(a.name));
    if (keys.length) definitions.push(`  PRIMARY KEY (${keys.join(", ")})`);
    for (const group of table.uniqueGroups)
      definitions.push(`  UNIQUE (${group.map(quote).join(", ")})`);
    parts.push(
      `CREATE TABLE ${quote(table.name)} (\n${definitions.join(",\n")}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`,
    );
  }
  // Add constraints after all tables exist, including schemas with cyclic references.
  const constraints = ordered.flatMap((table) =>
    table.foreignKeys.map(
      (fk) =>
        `ALTER TABLE ${quote(table.name)}\n  ADD CONSTRAINT ${quote(fk.name)}\n  FOREIGN KEY (${fk.columns.map(quote).join(", ")})\n  REFERENCES ${quote(fk.referencedTable)} (${fk.referencedColumns.map(quote).join(", ")});`,
    ),
  );
  if (constraints.length)
    parts.push("-- Relationships\n" + constraints.join("\n\n"));
  return parts.join("\n\n") + "\n";
}
