import type { Attribute, RelationalSchema } from "../domain/types";
import { orderedTables, sqlType } from "./mysql";
export const quotePostgres = (name: string) =>
  '"' + name.replace(/"/g, '""') + '"';
function defaultPostgres(a: Attribute): string {
  const value = a.defaultValue;
  if (value === undefined || value === "") return "";
  if (
    /^CURRENT_TIMESTAMP(?:\(\))?$/i.test(value) &&
    ["TIMESTAMP", "DATETIME"].includes(a.type)
  )
    return " DEFAULT CURRENT_TIMESTAMP";
  if (/^CURRENT_DATE(?:\(\))?$/i.test(value) && a.type === "DATE")
    return " DEFAULT CURRENT_DATE";
  if (a.type === "BOOLEAN" && /^(?:true|false|0|1)$/i.test(value))
    return ` DEFAULT ${/^(?:true|1)$/i.test(value) ? "TRUE" : "FALSE"}`;
  if (
    ["INT", "BIGINT", "DECIMAL"].includes(a.type) &&
    /^-?\d+(?:\.\d+)?$/.test(value)
  )
    return ` DEFAULT ${value}`;
  // E strings preserve backslashes independently of standard_conforming_strings.
  const literal = value.replace(/\\/g, "\\\\").replace(/'/g, "''");
  return ` DEFAULT ${value.includes("\\") ? "E" : ""}'${literal}'`;
}
export function generatePostgreSQL(
  schema: RelationalSchema,
  projectName = "SchemaForge project",
): string {
  if (!schema.tables.length)
    return "-- Add your first entity to start generating SQL.";
  const ordered = orderedTables(schema);
  const parts = [
    `-- ${projectName.replace(/[\r\n]/g, " ")}\n-- Generated by SchemaForge · PostgreSQL 10+\n-- Derived from your conceptual model\n`,
  ];
  if (schema.enforcementNotes?.length)
    parts.push(
      "-- Specialization rules requiring additional enforcement\n" +
        schema.enforcementNotes
          .map((note) => "-- " + note.replace(/[\r\n]/g, " "))
          .join("\n"),
    );
  for (const table of ordered) {
    const definitions = table.columns.map(
      (a) =>
        `  ${quotePostgres(a.name)} ${sqlType(a, "postgresql")}${a.autoIncrement ? " GENERATED BY DEFAULT AS IDENTITY" : ""}${!a.nullable || a.primaryKey ? " NOT NULL" : ""}${defaultPostgres(a)}${a.unique && !a.primaryKey ? " UNIQUE" : ""}`,
    );
    const keys = table.columns
      .filter((c) => c.primaryKey)
      .map((c) => quotePostgres(c.name));
    if (keys.length) definitions.push(`  PRIMARY KEY (${keys.join(", ")})`);
    for (const group of table.uniqueGroups)
      definitions.push(`  UNIQUE (${group.map(quotePostgres).join(", ")})`);
    parts.push(
      `CREATE TABLE ${quotePostgres(table.name)} (\n${definitions.join(",\n")}\n);`,
    );
  }
  const constraints = ordered.flatMap((table) =>
    table.foreignKeys.map(
      (fk) =>
        `ALTER TABLE ${quotePostgres(table.name)}\n  ADD CONSTRAINT ${quotePostgres(fk.name)}\n  FOREIGN KEY (${fk.columns.map(quotePostgres).join(", ")})\n  REFERENCES ${quotePostgres(fk.referencedTable)} (${fk.referencedColumns.map(quotePostgres).join(", ")});`,
    ),
  );
  if (constraints.length)
    parts.push("-- Relationships\n" + constraints.join("\n\n"));
  return parts.join("\n\n") + "\n";
}
