import { describe, expect, it } from "vitest";
import { attribute, emptySchema, sampleSchema } from "../domain/sample";
import type { ConceptualSchema } from "../domain/types";
import { toRelational } from "./transform";
import { generateSQL } from "./sql";
import { generatePostgreSQL, quotePostgres } from "./postgresql";
import { projectEngine } from "./engine";
import { isSchema } from "./persistence";
import { validateSchema } from "./validation";
const titles = (schema: ConceptualSchema) =>
  validateSchema(schema)
    .filter((i) => i.severity === "error")
    .map((i) => i.title);
describe("database engine settings and SQL generation", () => {
  it("keeps legacy projects on MySQL and validates engine settings on import", () => {
    expect(projectEngine(emptySchema())).toBe("mysql");
    for (const engine of ["none", "mysql", "postgresql"] as const)
      expect(isSchema({ ...sampleSchema(), engine })).toBe(true);
    expect(isSchema({ ...sampleSchema(), engine: "sqlite" })).toBe(false);
    expect(isSchema({ ...sampleSchema(), engine: null })).toBe(false);
  });
  it("does not generate SQL with no engine selected", () => {
    expect(generateSQL(toRelational(sampleSchema()), "none")).toBe("");
  });
  it("generates distinct MySQL and PostgreSQL DDL from the same relational model", () => {
    const model = toRelational(sampleSchema());
    const mysql = generateSQL(model, "mysql"),
      pg = generateSQL(model, "postgresql");
    expect(mysql).toContain("AUTO_INCREMENT");
    expect(mysql).toContain("ENGINE=InnoDB");
    expect(mysql).toContain("`students`");
    expect(pg).toContain('CREATE TABLE "students"');
    expect(pg).toContain("GENERATED BY DEFAULT AS IDENTITY");
    expect(pg).toContain('REFERENCES "students" ("student_id")');
    expect(pg).toContain("DEFAULT CURRENT_DATE");
    expect(pg).not.toContain("AUTO_INCREMENT");
    expect(pg).not.toContain("ENGINE=");
    expect(pg).not.toContain("`");
    expect(pg.lastIndexOf("CREATE TABLE")).toBeLessThan(
      pg.indexOf("ALTER TABLE"),
    );
  });
  it("maps date-time, numeric, boolean, and escaped text defaults", () => {
    const s = sampleSchema();
    s.entities[0].attributes.push(
      attribute("created", "DATETIME", { defaultValue: "CURRENT_TIMESTAMP" }),
      attribute("amount", "DECIMAL", {
        precision: 12,
        scale: 3,
        defaultValue: "-12.5",
      }),
      attribute("enabled", "BOOLEAN", { defaultValue: "1" }),
      attribute("disabled", "BOOLEAN", { defaultValue: "0" }),
      attribute("notes", "TEXT", { defaultValue: "Sam's C:\\notes" }),
    );
    const sql = generatePostgreSQL(toRelational(s));
    expect(sql).toContain(
      '"created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
    );
    expect(sql).toContain('"amount" NUMERIC(12,3) NOT NULL DEFAULT -12.5');
    expect(sql).toContain('"enabled" BOOLEAN NOT NULL DEFAULT TRUE');
    expect(sql).toContain('"disabled" BOOLEAN NOT NULL DEFAULT FALSE');
    expect(sql).toContain("DEFAULT E'Sam''s C:\\\\notes'");
    expect(quotePostgres('a"b')).toBe('"a""b"');
  });
  it("uses engine-specific identifier limits", () => {
    const s = sampleSchema();
    s.entities[0].name = "a".repeat(64);
    expect(titles({ ...s, engine: "mysql" })).not.toContain(
      "Invalid entity name",
    );
    expect(titles({ ...s, engine: "postgresql" })).toContain(
      "Invalid entity name",
    );
    s.entities[0].name = "a".repeat(90);
    expect(titles({ ...s, engine: "none" })).not.toContain(
      "Invalid entity name",
    );
  });
  it("does not apply InnoDB index restrictions to PostgreSQL or no engine", () => {
    const s = sampleSchema();
    s.entities[0].attributes.push(
      attribute("code", "TEXT", { unique: true }),
      attribute("wide", "VARCHAR", { length: 1000, unique: true }),
    );
    expect(titles(s)).toEqual(
      expect.arrayContaining([
        "TEXT cannot be a complete index",
        "Unique index is too large",
      ]),
    );
    expect(titles({ ...s, engine: "postgresql" })).toEqual([]);
    expect(titles({ ...s, engine: "none" })).toEqual([]);
  });
  it("validates PostgreSQL boolean and numeric defaults", () => {
    const s = sampleSchema();
    s.engine = "postgresql";
    s.entities[0].attributes.push(
      attribute("enabled", "BOOLEAN", { defaultValue: "2" }),
      attribute("count", "INT", { defaultValue: "true" }),
    );
    expect(titles(s)).toEqual(
      expect.arrayContaining([
        "Invalid boolean default",
        "Invalid numeric default",
      ]),
    );
  });
  it("permits PostgreSQL multiple identity columns and larger numeric precision", () => {
    const s = sampleSchema();
    s.entities[0].attributes.push(
      attribute("second_id", "INT", { primaryKey: true, autoIncrement: true }),
      attribute("precise", "DECIMAL", { precision: 90, scale: 40 }),
    );
    expect(titles(s)).toEqual(
      expect.arrayContaining([
        "Multiple auto-increment columns",
        "Invalid decimal precision",
      ]),
    );
    expect(titles({ ...s, engine: "postgresql" })).toEqual([]);
  });
  it("creates shared PK/FK subtype tables for PostgreSQL and keeps enforcement notes", () => {
    const s = sampleSchema();
    s.engine = "postgresql";
    s.entities.push({
      id: "sub",
      name: "graduates",
      description: "",
      color: "orange",
      attributes: [],
      position: { x: 0, y: 0 },
    });
    s.specializations = [
      {
        id: "isa",
        supertypeId: "students",
        subtypeIds: ["sub"],
        exclusivity: "disjoint",
        completeness: "total",
      },
    ];
    const sql = generateSQL(toRelational(s), "postgresql");
    expect(sql).toContain(
      'CREATE TABLE "graduates" (\n  "student_id" INT NOT NULL,\n  PRIMARY KEY ("student_id")',
    );
    expect(sql).toContain("total specialization requires application");
    expect(titles(s)).toEqual([]);
  });
  it("keeps generated PostgreSQL constraint names unique within the 63-byte limit", () => {
    const s = sampleSchema();
    s.engine = "postgresql";
    s.relationships[1].id = "a".repeat(100);
    s.relationships.push({ ...s.relationships[1], id: "a".repeat(100) + "b" });
    const names = toRelational(s).tables.flatMap((t) =>
      t.foreignKeys.map((fk) => fk.name),
    );
    expect(names.every((name) => name.length <= 63)).toBe(true);
    expect(new Set(names).size).toBe(names.length);
  });
  it("generates deterministic PostgreSQL without mutating the relational model", () => {
    const model = toRelational(sampleSchema()),
      before = structuredClone(model);
    expect(generatePostgreSQL(model)).toBe(generatePostgreSQL(model));
    expect(model).toEqual(before);
  });
});
